var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/stocks/route.js")
R.c("server/chunks/[root-of-the-server]__0456b404._.js")
R.c("server/chunks/src_lib_data_ts_ed9368ba._.js")
R.c("server/chunks/src_lib_0bc0568f._.js")
R.c("server/chunks/[root-of-the-server]__301a6c3e._.js")
R.c("server/chunks/6fb61_next_dist_esm_build_templates_app-route_e4e7d227.js")
R.c("server/chunks/[root-of-the-server]__c8b1f1cf._.js")
R.c("server/chunks/_next-internal_server_app_api_stocks_route_actions_eaba119b.js")
R.m(82253)
module.exports=R.m(82253).exports
