// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/backtesting" | "/charts" | "/community" | "/dashboard" | "/factors" | "/learn" | "/learn/[topic]" | "/ml-lab" | "/portfolio" | "/risk" | "/screener" | "/strategy-builder"
type AppRouteHandlerRoutes = "/api/ai/generate-strategy" | "/api/alerts" | "/api/alerts/rules" | "/api/analytics/icb-snapshot" | "/api/analytics/valuation-rankings" | "/api/assistant" | "/api/assistant/execute" | "/api/assistant/strategy-suggest" | "/api/backtesting" | "/api/data" | "/api/data/stocks/[symbol]" | "/api/factors" | "/api/finance-analysis" | "/api/finance-analysis/export" | "/api/fundamentals" | "/api/health" | "/api/health/data" | "/api/market-overview" | "/api/optimize" | "/api/preferences" | "/api/risk" | "/api/stocks" | "/api/stocks/batch" | "/api/strategies" | "/api/strategies/[id]" | "/api/strategy-lab/health" | "/api/strategy-lab/runs" | "/api/strategy-lab/runs/[runId]" | "/api/strategy-lab/runs/[runId]/cancel" | "/api/strategy-lab/runs/[runId]/events" | "/api/strategy-lab/runs/[runId]/result" | "/api/strategy-lab/strategies" | "/api/strategy-lab/worker/tick" | "/api/telemetry/ui-kpi"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/generate-strategy": {}
  "/api/alerts": {}
  "/api/alerts/rules": {}
  "/api/analytics/icb-snapshot": {}
  "/api/analytics/valuation-rankings": {}
  "/api/assistant": {}
  "/api/assistant/execute": {}
  "/api/assistant/strategy-suggest": {}
  "/api/backtesting": {}
  "/api/data": {}
  "/api/data/stocks/[symbol]": { "symbol": string; }
  "/api/factors": {}
  "/api/finance-analysis": {}
  "/api/finance-analysis/export": {}
  "/api/fundamentals": {}
  "/api/health": {}
  "/api/health/data": {}
  "/api/market-overview": {}
  "/api/optimize": {}
  "/api/preferences": {}
  "/api/risk": {}
  "/api/stocks": {}
  "/api/stocks/batch": {}
  "/api/strategies": {}
  "/api/strategies/[id]": { "id": string; }
  "/api/strategy-lab/health": {}
  "/api/strategy-lab/runs": {}
  "/api/strategy-lab/runs/[runId]": { "runId": string; }
  "/api/strategy-lab/runs/[runId]/cancel": { "runId": string; }
  "/api/strategy-lab/runs/[runId]/events": { "runId": string; }
  "/api/strategy-lab/runs/[runId]/result": { "runId": string; }
  "/api/strategy-lab/strategies": {}
  "/api/strategy-lab/worker/tick": {}
  "/api/telemetry/ui-kpi": {}
  "/backtesting": {}
  "/charts": {}
  "/community": {}
  "/dashboard": {}
  "/factors": {}
  "/learn": {}
  "/learn/[topic]": { "topic": string; }
  "/ml-lab": {}
  "/portfolio": {}
  "/risk": {}
  "/screener": {}
  "/strategy-builder": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
