var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/stocks/route.js")
R.c("server/chunks/[root-of-the-server]__ef15ffa3._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_577ef752.js")
R.c("server/chunks/src_lib_2486f1aa._.js")
R.c("server/chunks/[root-of-the-server]__581dfa99._.js")
R.c("server/chunks/src_lib_data_ts_ed9368ba._.js")
R.c("server/chunks/[root-of-the-server]__f408c708._.js")
R.c("server/chunks/_next-internal_server_app_api_stocks_route_actions_eaba119b.js")
R.m(4288)
module.exports=R.m(4288).exports
