var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/portfolio/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__9eb89fd6._.js")
R.c("server/chunks/ssr/_4f469f94._.js")
R.c("server/chunks/ssr/_584892a4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__90a1398b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9d96faef._.js")
R.c("server/chunks/ssr/6fb61_next_dist_a6267c2a._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/6fb61_next_dist_client_components_builtin_global-error_e3c29345.js")
R.c("server/chunks/ssr/[root-of-the-server]__6f56fd5c._.js")
R.c("server/chunks/ssr/6fb61_next_dist_client_components_81fd7193._.js")
R.c("server/chunks/ssr/6fb61_next_dist_client_components_builtin_forbidden_eb5cf4de.js")
R.c("server/chunks/ssr/6fb61_next_dist_client_components_builtin_unauthorized_2dc64234.js")
R.c("server/chunks/ssr/_next-internal_server_app_portfolio_page_actions_224c57fe.js")
R.m(31999)
module.exports=R.m(31999).exports
