var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/backtesting/route.js")
R.c("server/chunks/[root-of-the-server]__a471003f._.js")
R.c("server/chunks/6fb61_next_dist_esm_build_templates_app-route_0fc4b3b4.js")
R.c("server/chunks/src_lib_quant_31b4ba26._.js")
R.c("server/chunks/[root-of-the-server]__c8b1f1cf._.js")
R.c("server/chunks/[root-of-the-server]__301a6c3e._.js")
R.c("server/chunks/[root-of-the-server]__37e40bd1._.js")
R.c("server/chunks/_next-internal_server_app_api_backtesting_route_actions_7c5b8723.js")
R.m(20613)
module.exports=R.m(20613).exports
