var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/risk/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__cc67ce34._.js")
R.c("server/chunks/ssr/_4f469f94._.js")
R.c("server/chunks/ssr/_fa8952c5._.js")
R.c("server/chunks/ssr/[root-of-the-server]__90a1398b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9d96faef._.js")
R.c("server/chunks/ssr/6fb61_next_dist_a6267c2a._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/6fb61_next_dist_client_components_builtin_global-error_e3c29345.js")
R.c("server/chunks/ssr/src_b42164f4._.js")
R.c("server/chunks/ssr/6fb61_next_dist_client_components_81fd7193._.js")
R.c("server/chunks/ssr/6fb61_next_dist_client_components_builtin_forbidden_eb5cf4de.js")
R.c("server/chunks/ssr/6fb61_next_dist_client_components_builtin_unauthorized_2dc64234.js")
R.c("server/chunks/ssr/_next-internal_server_app_risk_page_actions_de0cb908.js")
R.m(25795)
module.exports=R.m(25795).exports
