var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/strategy-lab/health/route.js")
R.c("server/chunks/[root-of-the-server]__5de7feb2._.js")
R.c("server/chunks/src_lib_strategy-lab_orchestrator_ts_b22cfcb2._.js")
R.c("server/chunks/[root-of-the-server]__6227ba04._.js")
R.c("server/chunks/[root-of-the-server]__c8b1f1cf._.js")
R.c("server/chunks/[root-of-the-server]__301a6c3e._.js")
R.c("server/chunks/[root-of-the-server]__37e40bd1._.js")
R.c("server/chunks/_next-internal_server_app_api_strategy-lab_health_route_actions_7846f695.js")
R.m(41364)
module.exports=R.m(41364).exports
