var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/backtesting/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__dd07f047._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_212f5c15._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d773946e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__7f68cf2f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_3b10f78b._.js")
R.c("server/chunks/ssr/_045e994b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_backtesting_page_actions_af678376.js")
R.m(89998)
module.exports=R.m(89998).exports
