// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/backtesting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/backtesting">> = Specific
  const handler = {} as typeof import("../../src/app/backtesting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/charts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/charts">> = Specific
  const handler = {} as typeof import("../../src/app/charts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/factors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/factors">> = Specific
  const handler = {} as typeof import("../../src/app/factors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learn/[topic]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn/[topic]">> = Specific
  const handler = {} as typeof import("../../src/app/learn/[topic]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learn/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learn">> = Specific
  const handler = {} as typeof import("../../src/app/learn/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/ml-lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ml-lab">> = Specific
  const handler = {} as typeof import("../../src/app/ml-lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio">> = Specific
  const handler = {} as typeof import("../../src/app/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/risk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/risk">> = Specific
  const handler = {} as typeof import("../../src/app/risk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/screener/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/screener">> = Specific
  const handler = {} as typeof import("../../src/app/screener/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/icb-snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/icb-snapshot">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/icb-snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/analytics/valuation-rankings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/valuation-rankings">> = Specific
  const handler = {} as typeof import("../../src/app/api/analytics/valuation-rankings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assistant/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assistant/execute">> = Specific
  const handler = {} as typeof import("../../src/app/api/assistant/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/assistant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/assistant">> = Specific
  const handler = {} as typeof import("../../src/app/api/assistant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/backtesting/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backtesting">> = Specific
  const handler = {} as typeof import("../../src/app/api/backtesting/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/factors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/factors">> = Specific
  const handler = {} as typeof import("../../src/app/api/factors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/finance-analysis/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance-analysis/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/finance-analysis/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/finance-analysis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/finance-analysis">> = Specific
  const handler = {} as typeof import("../../src/app/api/finance-analysis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/fundamentals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fundamentals">> = Specific
  const handler = {} as typeof import("../../src/app/api/fundamentals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/data">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/market-overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/market-overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/market-overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/optimize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/optimize">> = Specific
  const handler = {} as typeof import("../../src/app/api/optimize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/risk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/risk">> = Specific
  const handler = {} as typeof import("../../src/app/api/risk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stocks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stocks">> = Specific
  const handler = {} as typeof import("../../src/app/api/stocks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
