var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/strategy-lab/strategies/route.js")
R.c("server/chunks/[root-of-the-server]__c8f62ec0._.js")
R.c("server/chunks/src_lib_data_ts_ed9368ba._.js")
R.c("server/chunks/[root-of-the-server]__6227ba04._.js")
R.c("server/chunks/[root-of-the-server]__c8b1f1cf._.js")
R.c("server/chunks/src_lib_strategy-lab_orchestrator_ts_b22cfcb2._.js")
R.c("server/chunks/[root-of-the-server]__301a6c3e._.js")
R.c("server/chunks/_next-internal_server_app_api_strategy-lab_strategies_route_actions_54b29f60.js")
R.m(15568)
module.exports=R.m(15568).exports
